# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70bd39ed75bf60d9270cb24694099dacea803148782b98ee15c65ddc17928c1f1166c71071c0f3489d19372f3091e2a7263069611b931a063b35102ee69a17f7

test:
  secret_key_base: e9255b68a9080d7901e9e92300414f4d4cfa54a4a6ea11d32e6a04a1edf113fb055097ea2c14c85765d7820e76767cba015f2efed48c76dbc96ec40355cdd590

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
